DROP TABLE IF EXISTS EMPLOYEE;
 
CREATE TABLE EMPLOYEE (
  id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(45) DEFAULT NULL,
  last_name VARCHAR(45) DEFAULT NULL,
  email VARCHAR(45) DEFAULT NULL,
  phone VARCHAR(45) DEFAULT NULL
);
